config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates_presence_of :title, :content
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, uniqueness: true
  has_many :posts
  has_many :comments

  include BCrypt

  has_secure_password

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Nope" if current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      UserMailer.answer_alert(@comment.post, @comment).deliver
      redirect_to posts_path, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to root_path, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
    @comment = Comment.new
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    if current_user.nil?
      redirect_to login_path, notice: "Please login to add a post."
    else
      @post = Post.new
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      UserMailer.posted_thank_you(@post.user).deliver
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in! You have memory!"
    else
      flash.now.alert = "Your memory is bad."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "BYE!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user.nil?
      @user = User.new
    else
      redirect_to root_path, notice: "You are already signed in."
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You rule"
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@comment.post, @comment], html: {class: "ui form", method:"patch"} do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit "Save Comment", class:"ui teal button"%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/home/index.html.erb
Hi!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ui secondary pointing teal inverted menu">
  <%= link_to "Home", root_path, class:"item" %>
  <div class="right menu">
    <% if current_user.nil? %>
      <%= link_to "Login", login_path, class:"item" %>
      <%= link_to "Sign Up", signup_path, class:"item" %>
    <% else %>
      <div class="item">Logged in as <%= current_user.username %></div>
      <%= link_to "Logout", logout_path, class:"item" %>
    <% end %>
  </div>
</div>

<div class="main-container ui container">
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {class: "ui form"} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit class:"ui teal button"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Latest Posts</h1>

<div class="ui accordion">
  <% @posts.each do |post| %>
    <div class="title ui header">
      <i class="dropdown icon"></i>
      <%= post.title %>
    </div>
    <div class="content ui segment">
      <div class="transition hidden">
        <div class="ui grey ribbon label"><%= distance_of_time_in_words_to_now(post.created_at) %> ago by <%= post.user.username %></div>
        <br>
        <br>
        <div class="content large"><%= simple_format(post.content) %></div>

        <div class="ui comments">
          <% if post.comments.any? %>
            <h3 class="ui dividing header teal">Answers</h3>
            <% post.comments.each do |comment| %>
              <div class="comment">
                <div class="content">
                  <div class="text">
                    <%= comment.comment %>
                  </div>
                  <a class="author">by <%= comment.user.username %></a>
                  <div class="metadata">
                    <span class="date"><%= distance_of_time_in_words_to_now(comment.created_at) %> ago</span>
                  </div>
                  <% if !current_user.nil? && comment.user.id == current_user.id %>
                    <div class="actions">
                      <%= link_to "edit", edit_post_comment_path(post, comment)%>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>
            <h3 class="ui dividing header teal">No comments yet.</h3>
          <% end %>
          <% if current_user.nil?%>
            <h3 class="ui dividing header teal">Sign in to add a comment</h3>
            <%= form_tag sessions_path, class: "ui form" do %>
              <div class="field">
                <%= label_tag :email %><br />
                <%= text_field_tag :email, params[:email] %>
              </div>
              <div class="field">
                <%= label_tag :password %><br />
                <%= password_field_tag :password %>
              </div>
              <div class="actions"><%= submit_tag "Log In" %></div>
            <% end %>
          <% else %>
            <h3 class="ui dividing header teal">Add a comment</h3>
            <%= form_for [post, @comment], html: {class: "ui form"} do |f| %>
              <div class="field">
                <%= f.label :comment %><br>
                <%= f.text_area :comment %>
              </div>
              <%= f.hidden_field :post_id, options = {value:post.id}%>
              <%= f.submit class:"ui button teal" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>
<% if !current_user.nil? %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign Up</h1>

<%= form_for @user, html: {class: "ui form"} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>